### ISSUE TITLE
Invalid_response  Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd

### ISSUE THREAD

**Issue by TungMaybach** [SAML-Toolkits/java-saml#414]
Hi team One Login

I testing SAML Java with ADFS Microsoft
I'm imported relaying party trust and claim attribute setup in ADFS
X509 Idp cert in Properties file ( SAML toolkit ) is token signing in ADFS
but when after log in ADFS, Saml Response result as in Picture

OS : MS server 2016
JDK : 18

Hope can help me !!
![Untitled](https://github.com/SAML-Toolkits/java-saml/assets/42497788/1f8f25aa-efcd-4bda-8e88-a4e70f5deae9)

![image](https://github.com/SAML-Toolkits/java-saml/assets/42497788/3d985cd4-615d-421e-ae37-5118ac775f3d)

**Comment by TungMaybach** [comment]
![2](https://github.com/SAML-Toolkits/java-saml/assets/42497788/84872882-de70-47a1-9a95-3bfd77bc13ca)

**Comment by haavar** [comment]
Can you provide a HAR file from when you are seeing the issue?

**Comment by ben-manes** [comment]
I see something similar when upgrading to jdk21 (from 14). It also has the error
```java
org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'xop:Include' to a(n) 'element declaration' component.
	at c.s.o.a.x.i.u.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at c.s.o.a.x.i.u.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	... 11 frames excluded
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:612)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:644)
	at c.onelogin.saml2.util.SchemaFactory.loadFromUrl(SchemaFactory.java:106)
	at com.onelogin.saml2.util.Util.validateXML(Util.java:305)
	at c.onelogin.saml2.authn.SamlResponse.isValid(SamlResponse.java:220)
	at com.onelogin.saml2.Auth.processResponse(Auth.java:1202)
	at com.onelogin.saml2.Auth.processResponse(Auth.java:1248)
	at c.l.s.e.t.u.auth.OAuthTokenAction.processSamlResponse(OAuthTokenAction.java:241)
	at c.l.s.e.t.u.auth.OAuthTokenAction.samlSignOn(OAuthTokenAction.java:141)
	at j.i.r.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.lang.reflect.Method.invoke(Method.java:580)
	at o.j.r.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at o.j.r.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at o.j.r.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at o.j.r.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at o.j.r.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at o.j.r.c.i.j.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at o.j.r.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	... 70 frames truncated
```
